import Foundation

public enum MeshPLYWriter {
    public static func write(_ source: MeshAsset, to url: URL) throws {
        let mesh = source.normals == nil ? try source.withGeneratedNormals() : source
        let hasColors = mesh.colorsRGBA8 != nil
        var header = """
        ply
        format binary_little_endian 1.0
        comment Generated by mere.run native Asset3D
        comment coordinate_system \(mesh.coordinateSystem.rawValue)
        comment units \(mesh.units.rawValue)
        element vertex \(mesh.vertexCount)
        property float x
        property float y
        property float z
        property float nx
        property float ny
        property float nz
        """
        header += "\n"
        if hasColors {
            header += "property uchar red\nproperty uchar green\nproperty uchar blue\nproperty uchar alpha\n"
        }
        header += "element face \(mesh.triangleCount)\nproperty list uchar uint vertex_indices\nend_header\n"

        var data = Data(header.utf8)
        for vertex in 0..<mesh.vertexCount {
            let base = vertex * 3
            appendFloat(mesh.vertices[base], to: &data)
            appendFloat(mesh.vertices[base + 1], to: &data)
            appendFloat(mesh.vertices[base + 2], to: &data)
            appendFloat(mesh.normals![base], to: &data)
            appendFloat(mesh.normals![base + 1], to: &data)
            appendFloat(mesh.normals![base + 2], to: &data)
            if let colors = mesh.colorsRGBA8 {
                let color = vertex * 4
                data.append(contentsOf: colors[color..<(color + 4)])
            }
        }
        for triangle in stride(from: 0, to: mesh.indices.count, by: 3) {
            data.append(3)
            appendUInt32(mesh.indices[triangle], to: &data)
            appendUInt32(mesh.indices[triangle + 1], to: &data)
            appendUInt32(mesh.indices[triangle + 2], to: &data)
        }
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try data.write(to: url, options: .atomic)
    }

    private static func appendFloat(_ value: Float, to data: inout Data) {
        appendUInt32(value.bitPattern, to: &data)
    }

    private static func appendUInt32(_ value: UInt32, to data: inout Data) {
        var value = value.littleEndian
        withUnsafeBytes(of: &value) { data.append(contentsOf: $0) }
    }
}
