import Foundation

public enum MeshOBJWriter {
    public static func write(_ source: MeshAsset, to url: URL) throws {
        let mesh = source.normals == nil ? try source.withGeneratedNormals() : source
        let normals = mesh.normals!
        var output = "# Generated by mere.run native Asset3D\n"
        output += "# coordinate_system \(mesh.coordinateSystem.rawValue)\n"
        output += "# units \(mesh.units.rawValue)\n"
        for vertex in 0..<mesh.vertexCount {
            let base = vertex * 3
            output += "v \(format(mesh.vertices[base])) \(format(mesh.vertices[base + 1])) \(format(mesh.vertices[base + 2]))"
            if let colors = mesh.colorsRGBA8 {
                let color = vertex * 4
                output += " \(format(Float(colors[color]) / 255)) \(format(Float(colors[color + 1]) / 255)) \(format(Float(colors[color + 2]) / 255))"
            }
            output += "\n"
        }
        if let uv = mesh.textureCoordinates {
            for vertex in 0..<mesh.vertexCount {
                output += "vt \(format(uv[vertex * 2])) \(format(uv[vertex * 2 + 1]))\n"
            }
        }
        for vertex in 0..<mesh.vertexCount {
            let base = vertex * 3
            output += "vn \(format(normals[base])) \(format(normals[base + 1])) \(format(normals[base + 2]))\n"
        }
        for triangle in stride(from: 0, to: mesh.indices.count, by: 3) {
            output += "f"
            for corner in 0..<3 {
                let index = Int(mesh.indices[triangle + corner]) + 1
                output += mesh.textureCoordinates == nil ? " \(index)//\(index)" : " \(index)/\(index)/\(index)"
            }
            output += "\n"
        }
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try Data(output.utf8).write(to: url, options: .atomic)
    }

    private static func format(_ value: Float) -> String {
        String(format: "%.9g", Double(value))
    }
}
