#!/usr/bin/env python3
"""Compare mere.run unified-AV audio against an upstream LTX-2 output.

The script is intentionally media-file based: run the same prompt/seed through
mere.run and upstream LTX-2, then compare the produced MP4s. It reports both
container/codec metadata and decoded waveform stats so odd audio can be traced
to either the model waveform or the mux/encode step.
"""

from __future__ import annotations

import argparse
import array
import json
import math
import os
import re
import shutil
import struct
import subprocess
import sys
from pathlib import Path
from typing import Any


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]

    try:
        ffprobe = resolve_tool("MERERUN_FFPROBE", "ffprobe")
        ffmpeg = resolve_tool("MERERUN_FFMPEG", "ffmpeg")

        mere = analyze_media(Path(args.mere), ffprobe, ffmpeg)
        ltx = analyze_media(Path(args.ltx), ffprobe, ffmpeg)
        comparison = compare_reports(mere, ltx)

        local_reference = inspect_local_reference(repo_root)
        upstream_reference = inspect_ltx_repo(Path(args.ltx_repo)) if args.ltx_repo else None
        model_reference = inspect_model_root(Path(args.model_root)) if args.model_root else None

        warnings = list(comparison["warnings"])
        warnings.extend(reference_warnings(local_reference, upstream_reference, model_reference))

        report = {
            "mere": mere,
            "ltx": ltx,
            "comparison": comparison,
            "references": {
                "local": local_reference,
                "ltx_repo": upstream_reference,
                "model_root": model_reference,
            },
            "warnings": warnings,
        }

        if args.json_out:
            output_path = Path(args.json_out)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")

        if not args.quiet:
            print_human_report(report)

        if warnings and args.fail_on_warning:
            return 2
        return 0
    except DiagnosticError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Compare a mere.run unified-av MP4 against an upstream LTX-2 MP4 "
            "using ffprobe metadata, decoded PCM stats, and source-reference checks."
        )
    )
    parser.add_argument("--mere", required=True, help="MP4 generated by mere.run --variant unified-av.")
    parser.add_argument("--ltx", required=True, help="MP4 generated by the upstream LTX-2 pipeline.")
    parser.add_argument(
        "--ltx-repo",
        help="Optional path to a local Lightricks/LTX-2 checkout for source-default inspection.",
    )
    parser.add_argument(
        "--model-root",
        help="Optional local video-ltx-av model root to scan for audio/vocoder config hints.",
    )
    parser.add_argument("--json-out", help="Optional path for a full JSON report.")
    parser.add_argument("--fail-on-warning", action="store_true", help="Exit 2 when drift warnings are detected.")
    parser.add_argument("--quiet", action="store_true", help="Only write --json-out; do not print the text report.")
    return parser.parse_args()


class DiagnosticError(RuntimeError):
    pass


def resolve_tool(env_name: str, default_name: str) -> str:
    override = os.environ.get(env_name)
    if override:
        if Path(override).is_file() and os.access(override, os.X_OK):
            return override
        raise DiagnosticError(f"{env_name} points to a non-executable file: {override}")

    resolved = shutil.which(default_name)
    if resolved:
        return resolved
    raise DiagnosticError(f"{default_name} was not found on PATH; install ffmpeg or set {env_name}.")


def run_command(command: list[str], *, text: bool = True) -> subprocess.CompletedProcess[str] | subprocess.CompletedProcess[bytes]:
    try:
        return subprocess.run(command, check=False, capture_output=True, text=text)
    except OSError as error:
        raise DiagnosticError(f"failed to run {command[0]}: {error}") from error


def analyze_media(path: Path, ffprobe: str, ffmpeg: str) -> dict[str, Any]:
    if not path.is_file():
        raise DiagnosticError(f"media file does not exist: {path}")

    probe = ffprobe_json(path, ffprobe)
    audio = first_stream(probe, "audio")
    video = first_stream(probe, "video")
    if audio is None:
        raise DiagnosticError(f"{path} has no audio stream")

    sample_rate = int_or_none(audio.get("sample_rate"))
    highpass_cutoff = highpass_cutoff_for(sample_rate)
    pcm = pcm_stats(path, ffmpeg)
    high = pcm_stats(path, ffmpeg, audio_filter=f"highpass=f={highpass_cutoff}")
    loudness = ebur128_stats(path, ffmpeg)

    highpass_ratio_db = None
    if pcm["rms_linear"] and high["rms_linear"]:
        highpass_ratio_db = db(high["rms_linear"] / pcm["rms_linear"])

    return {
        "path": str(path),
        "format": summarize_format(probe.get("format", {})),
        "audio_stream": summarize_audio_stream(audio),
        "video_stream": summarize_video_stream(video) if video else None,
        "decoded_audio": {
            **pcm,
            "highpass_cutoff_hz": highpass_cutoff,
            "highpass_rms_dbfs": high["rms_dbfs"],
            "highpass_to_full_rms_db": highpass_ratio_db,
        },
        "loudness": loudness,
    }


def ffprobe_json(path: Path, ffprobe: str) -> dict[str, Any]:
    result = run_command(
        [
            ffprobe,
            "-v",
            "error",
            "-show_format",
            "-show_streams",
            "-of",
            "json",
            str(path),
        ]
    )
    if result.returncode != 0:
        raise DiagnosticError(f"ffprobe failed for {path}: {result.stderr.strip()}")
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError as error:
        raise DiagnosticError(f"ffprobe returned invalid JSON for {path}: {error}") from error


def first_stream(probe: dict[str, Any], kind: str) -> dict[str, Any] | None:
    for stream in probe.get("streams", []):
        if stream.get("codec_type") == kind:
            return stream
    return None


def summarize_format(format_info: dict[str, Any]) -> dict[str, Any]:
    return {
        "format_name": format_info.get("format_name"),
        "duration_s": float_or_none(format_info.get("duration")),
        "bit_rate_bps": int_or_none(format_info.get("bit_rate")),
        "size_bytes": int_or_none(format_info.get("size")),
    }


def summarize_audio_stream(stream: dict[str, Any]) -> dict[str, Any]:
    return {
        "codec_name": stream.get("codec_name"),
        "profile": stream.get("profile"),
        "sample_fmt": stream.get("sample_fmt"),
        "sample_rate_hz": int_or_none(stream.get("sample_rate")),
        "channels": int_or_none(stream.get("channels")),
        "channel_layout": stream.get("channel_layout"),
        "bit_rate_bps": int_or_none(stream.get("bit_rate")),
        "duration_s": float_or_none(stream.get("duration")),
        "time_base": stream.get("time_base"),
    }


def summarize_video_stream(stream: dict[str, Any]) -> dict[str, Any]:
    return {
        "codec_name": stream.get("codec_name"),
        "profile": stream.get("profile"),
        "pix_fmt": stream.get("pix_fmt"),
        "width": int_or_none(stream.get("width")),
        "height": int_or_none(stream.get("height")),
        "avg_frame_rate": stream.get("avg_frame_rate"),
        "fps": fraction_to_float(stream.get("avg_frame_rate")),
        "bit_rate_bps": int_or_none(stream.get("bit_rate")),
        "duration_s": float_or_none(stream.get("duration")),
        "nb_frames": int_or_none(stream.get("nb_frames")),
    }


def pcm_stats(path: Path, ffmpeg: str, audio_filter: str | None = None) -> dict[str, Any]:
    command = [
        ffmpeg,
        "-v",
        "error",
        "-i",
        str(path),
        "-map",
        "0:a:0",
        "-vn",
        "-ac",
        "2",
    ]
    if audio_filter:
        command += ["-af", audio_filter]
    command += ["-f", "f32le", "pipe:1"]

    try:
        process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except OSError as error:
        raise DiagnosticError(f"failed to run ffmpeg for {path}: {error}") from error

    if process.stdout is None or process.stderr is None:
        raise DiagnosticError("failed to capture ffmpeg output")

    count = 0
    frames = 0
    nonfinite = 0
    total = 0.0
    sumsq = 0.0
    peak = 0.0
    clip = 0
    near_clip = 0
    zero_crossings = [0, 0]
    previous: list[float | None] = [None, None]
    leftover = b""
    channel_count = 2

    while True:
        chunk = process.stdout.read(1024 * 1024)
        if not chunk:
            break
        data = leftover + chunk
        usable = len(data) - (len(data) % 4)
        leftover = data[usable:]
        if usable == 0:
            continue

        values = array.array("f")
        values.frombytes(data[:usable])
        if sys.byteorder != "little":
            values.byteswap()

        for value in values:
            channel = count % channel_count
            count += 1
            if not math.isfinite(value):
                nonfinite += 1
                continue
            abs_value = abs(value)
            peak = max(peak, abs_value)
            total += value
            sumsq += value * value
            if abs_value >= 0.999:
                clip += 1
            if abs_value >= 0.98:
                near_clip += 1
            prev = previous[channel]
            if prev is not None and ((prev < 0 <= value) or (prev >= 0 > value)):
                zero_crossings[channel] += 1
            previous[channel] = value

    stderr = process.stderr.read().decode("utf-8", errors="replace")
    status = process.wait()
    if status != 0:
        raise DiagnosticError(f"ffmpeg audio decode failed for {path}: {stderr.strip()}")

    finite_count = max(0, count - nonfinite)
    frames = count // channel_count
    rms = math.sqrt(sumsq / finite_count) if finite_count else 0.0
    mean = total / finite_count if finite_count else 0.0
    peak_db = db(peak)
    rms_db = db(rms)

    return {
        "channels_decoded": channel_count,
        "frames_decoded": frames,
        "samples_decoded": count,
        "nonfinite_samples": nonfinite,
        "peak_linear": peak,
        "peak_dbfs": peak_db,
        "rms_linear": rms,
        "rms_dbfs": rms_db,
        "crest_db": none_if_inf(peak_db - rms_db) if peak > 0 and rms > 0 else None,
        "dc_offset": mean,
        "clip_sample_ratio": clip / finite_count if finite_count else None,
        "near_clip_sample_ratio": near_clip / finite_count if finite_count else None,
        "zero_crossing_rate": sum(zero_crossings) / finite_count if finite_count else None,
    }


def ebur128_stats(path: Path, ffmpeg: str) -> dict[str, Any]:
    result = run_command(
        [
            ffmpeg,
            "-hide_banner",
            "-nostats",
            "-i",
            str(path),
            "-map",
            "0:a:0",
            "-filter:a",
            "ebur128=peak=true",
            "-f",
            "null",
            "-",
        ]
    )
    if result.returncode != 0:
        return {"error": result.stderr.strip()}

    stderr = result.stderr
    integrated = last_float_match(r"I:\s*(-?\d+(?:\.\d+)?)\s+LUFS", stderr)
    lra = last_float_match(r"LRA:\s*(-?\d+(?:\.\d+)?)\s+LU", stderr)
    true_peak = last_float_match(r"Peak:\s*(-?\d+(?:\.\d+)?)\s+dBFS", stderr)
    return {
        "integrated_lufs": integrated,
        "loudness_range_lu": lra,
        "true_peak_dbfs": true_peak,
    }


def compare_reports(mere: dict[str, Any], ltx: dict[str, Any]) -> dict[str, Any]:
    deltas = {
        "audio_sample_rate_hz": delta(
            mere["audio_stream"].get("sample_rate_hz"), ltx["audio_stream"].get("sample_rate_hz")
        ),
        "audio_bit_rate_bps": delta(
            mere["audio_stream"].get("bit_rate_bps"), ltx["audio_stream"].get("bit_rate_bps")
        ),
        "duration_s": delta(mere["format"].get("duration_s"), ltx["format"].get("duration_s")),
        "integrated_lufs": delta(
            mere["loudness"].get("integrated_lufs"), ltx["loudness"].get("integrated_lufs")
        ),
        "true_peak_dbfs": delta(mere["loudness"].get("true_peak_dbfs"), ltx["loudness"].get("true_peak_dbfs")),
        "peak_dbfs": delta(mere["decoded_audio"].get("peak_dbfs"), ltx["decoded_audio"].get("peak_dbfs")),
        "rms_dbfs": delta(mere["decoded_audio"].get("rms_dbfs"), ltx["decoded_audio"].get("rms_dbfs")),
        "crest_db": delta(mere["decoded_audio"].get("crest_db"), ltx["decoded_audio"].get("crest_db")),
        "near_clip_sample_ratio": delta(
            mere["decoded_audio"].get("near_clip_sample_ratio"), ltx["decoded_audio"].get("near_clip_sample_ratio")
        ),
        "highpass_to_full_rms_db": delta(
            mere["decoded_audio"].get("highpass_to_full_rms_db"),
            ltx["decoded_audio"].get("highpass_to_full_rms_db"),
        ),
    }

    warnings = []
    mere_audio = mere["audio_stream"]
    ltx_audio = ltx["audio_stream"]
    if mere_audio.get("sample_rate_hz") != ltx_audio.get("sample_rate_hz"):
        warnings.append(
            "audio sample rates differ: "
            f"mere={mere_audio.get('sample_rate_hz')} Hz, ltx={ltx_audio.get('sample_rate_hz')} Hz"
        )
    if mere_audio.get("codec_name") != ltx_audio.get("codec_name"):
        warnings.append(
            f"audio codecs differ: mere={mere_audio.get('codec_name')}, ltx={ltx_audio.get('codec_name')}"
        )
    if mere_audio.get("sample_fmt") != ltx_audio.get("sample_fmt"):
        warnings.append(
            f"audio sample formats differ: mere={mere_audio.get('sample_fmt')}, ltx={ltx_audio.get('sample_fmt')}"
        )

    bit_delta = deltas["audio_bit_rate_bps"]
    ltx_bit_rate = ltx_audio.get("bit_rate_bps")
    if bit_delta is not None and ltx_bit_rate:
        ratio = abs(bit_delta) / max(1, ltx_bit_rate)
        if ratio > 0.25:
            warnings.append(
                "audio bitrates differ by more than 25 percent: "
                f"mere={mere_audio.get('bit_rate_bps')} bps, ltx={ltx_bit_rate} bps"
            )

    duration_delta = deltas["duration_s"]
    if duration_delta is not None and abs(duration_delta) > 0.05:
        warnings.append(f"container durations differ by {duration_delta:+.3f}s")

    add_hot_audio_warnings("mere", mere, warnings)
    add_hot_audio_warnings("ltx", ltx, warnings)
    add_video_timing_warnings("mere", mere, warnings)
    add_video_timing_warnings("ltx", ltx, warnings)
    return {"deltas_mere_minus_ltx": deltas, "warnings": warnings}


def add_hot_audio_warnings(label: str, report: dict[str, Any], warnings: list[str]) -> None:
    decoded = report["decoded_audio"]
    loudness = report["loudness"]
    peak = decoded.get("peak_dbfs")
    true_peak = loudness.get("true_peak_dbfs")
    near_clip = decoded.get("near_clip_sample_ratio")
    crest = decoded.get("crest_db")
    lufs = loudness.get("integrated_lufs")

    if peak is not None and peak > -0.1:
        warnings.append(f"{label} decoded peak is within 0.1 dBFS of full scale ({peak:.2f} dBFS)")
    if true_peak is not None and true_peak > -1.0:
        warnings.append(f"{label} true peak is hotter than -1 dBFS ({true_peak:.2f} dBFS)")
    if near_clip is not None and near_clip > 0.001:
        warnings.append(f"{label} has {near_clip * 100:.3f}% samples at or above 0.98 full scale")
    if crest is not None and crest < 6.0:
        warnings.append(f"{label} crest factor is low ({crest:.2f} dB), which can sound overdriven")
    if lufs is not None and lufs > -12.0:
        warnings.append(f"{label} integrated loudness is hot ({lufs:.2f} LUFS)")


def add_video_timing_warnings(label: str, report: dict[str, Any], warnings: list[str]) -> None:
    video = report.get("video_stream") or {}
    fps = video.get("fps")
    if fps is not None and abs(fps - 24.0) > 0.1:
        warnings.append(
            f"{label} video stream is {fps:.2f} fps; LTX 2.3 unified AV timing should normally be rendered at 24 fps"
        )


def inspect_local_reference(repo_root: Path) -> dict[str, Any]:
    ffmpeg_io = read_text(repo_root / "Sources/MediaIO/FFmpegMediaIO.swift")
    apple_io = read_text(repo_root / "Sources/MediaIO/AppleMediaVideoIO.swift")
    writer = read_text(repo_root / "Sources/MereRunCore/LTX/LTXVideoMP4Writer.swift")
    generator = read_text(repo_root / "Sources/MereRunCore/LTX/LTXDistilledLatentGenerator.swift")
    video_command = read_text(repo_root / "Sources/MereRunCLI/Commands/VideoCommand.swift")
    mux_block = extract_swift_func(ffmpeg_io, "static func mux")

    sample_rate = None
    match = re.search(r"private let LTXAudioSampleRate\s*=\s*([0-9_]+)", generator)
    if match:
        sample_rate = int(match.group(1).replace("_", ""))

    return {
        "audio_sample_rate_hz": sample_rate,
        "stages_float_wav_before_mux": "writeFloatWAV" in writer,
        "audio_clamps_before_encode": "max(-1.0, sample)" in writer,
        "ffmpeg_mux_audio_codec": "aac" if '"-c:a", "aac"' in mux_block else None,
        "ffmpeg_mux_explicit_audio_bitrate": '"-b:a"' in mux_block,
        "apple_mux_export_preset": "AVAssetExportPresetHighestQuality"
        if "AVAssetExportPresetHighestQuality" in apple_io
        else None,
        "vocoder_with_bwe_supported": "VocoderWithBWE" in generator,
        "passes_generation_audio_sample_rate_to_writer": "audioSampleRate: result.audioSampleRate" in video_command,
    }


def inspect_ltx_repo(repo: Path) -> dict[str, Any]:
    if not repo.is_dir():
        raise DiagnosticError(f"--ltx-repo does not exist or is not a directory: {repo}")

    media_io_path, media_io = read_first_text(
        repo,
        [
            "packages/ltx-pipelines/src/ltx_pipelines/utils/media_io.py",
            "packages/ltx-pipelines-mlx/src/ltx_pipelines_mlx/utils/media_io.py",
        ],
    )
    configurator_path, configurator = read_first_text(
        repo,
        [
            "packages/ltx-core/src/ltx_core/model/audio_vae/model_configurator.py",
            "packages/ltx-core-mlx/src/ltx_core_mlx/model/audio_vae/bwe.py",
        ],
    )
    blocks = read_text(repo / "packages/ltx-pipelines-mlx/src/ltx_pipelines_mlx/utils/blocks.py")
    commit = git_commit(repo)
    crf = regex_group(r"def encode_video\([\s\S]*?crf:\s*int\s*=\s*([0-9]+)", media_io)
    preset = regex_group(r"def encode_video\([\s\S]*?preset:\s*str\s*=\s*\"([^\"]+)\"", media_io)

    return {
        "path": str(repo),
        "commit": commit,
        "media_io_path": str(media_io_path.relative_to(repo)) if media_io_path else None,
        "audio_vocoder_path": str(configurator_path.relative_to(repo)) if configurator_path else None,
        "encode_video_audio_codec": "aac" if 'add_stream("aac"' in media_io else None,
        "encode_video_default_crf": int(crf) if crf else None,
        "encode_video_default_preset": preset,
        "audio_clamps_before_encode": "torch.clip(samples, -1.0, 1.0)" in media_io,
        "audio_ingest_format": "s16" if 'format="s16"' in media_io and "torch.int16" in media_io else None,
        "vocoder_with_bwe_supported": "VocoderWithBWE" in configurator or "VocoderWithBWE()" in blocks,
    }


def inspect_model_root(root: Path) -> dict[str, Any]:
    if not root.is_dir():
        raise DiagnosticError(f"--model-root does not exist or is not a directory: {root}")

    json_files = sorted(root.rglob("*.json"))
    result: dict[str, Any] = {
        "path": str(root),
        "json_files_scanned": 0,
        "bwe_config_found": False,
        "vocoder_output_sampling_rates": [],
        "audio_model_sampling_rates": [],
        "files_with_audio_config": [],
        "safetensors_files_scanned": 0,
        "bwe_weight_keys_found": False,
        "files_with_bwe_weights": [],
    }

    for path in json_files[:500]:
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError, UnicodeDecodeError):
            continue
        result["json_files_scanned"] += 1
        found = collect_audio_config(data, result)
        if found:
            result["files_with_audio_config"].append(str(path.relative_to(root)))

    result["vocoder_output_sampling_rates"] = sorted(set(result["vocoder_output_sampling_rates"]))
    result["audio_model_sampling_rates"] = sorted(set(result["audio_model_sampling_rates"]))

    for path in sorted(root.rglob("*.safetensors"))[:50]:
        keys = safetensors_keys(path)
        if keys is None:
            continue
        result["safetensors_files_scanned"] += 1
        if any(is_bwe_weight_key(key) for key in keys):
            result["bwe_weight_keys_found"] = True
            result["files_with_bwe_weights"].append(str(path.relative_to(root)))

    return result


def safetensors_keys(path: Path) -> list[str] | None:
    try:
        with path.open("rb") as handle:
            size_bytes = handle.read(8)
            if len(size_bytes) != 8:
                return None
            header_size = struct.unpack("<Q", size_bytes)[0]
            header = handle.read(header_size)
        data = json.loads(header)
    except (OSError, json.JSONDecodeError, UnicodeDecodeError, struct.error):
        return None
    return [key for key in data if key != "__metadata__"]


def is_bwe_weight_key(key: str) -> bool:
    return (
        key.startswith("vocoder.bwe_generator.")
        or key.startswith("vocoder.mel_stft.")
        or key.startswith("vocoder.vocoder.")
    )


def collect_audio_config(value: Any, result: dict[str, Any]) -> bool:
    found = False
    if isinstance(value, dict):
        if "audio_vae" in value or "vocoder" in value or "bwe" in value:
            found = True
        if "bwe" in value and isinstance(value["bwe"], dict):
            result["bwe_config_found"] = True
        if "output_sampling_rate" in value:
            maybe_append_int(result["vocoder_output_sampling_rates"], value["output_sampling_rate"])
        if "sampling_rate" in value:
            maybe_append_int(result["audio_model_sampling_rates"], value["sampling_rate"])
        for child in value.values():
            found = collect_audio_config(child, result) or found
    elif isinstance(value, list):
        for child in value:
            found = collect_audio_config(child, result) or found
    return found


def reference_warnings(
    local: dict[str, Any],
    upstream: dict[str, Any] | None,
    model_root: dict[str, Any] | None,
) -> list[str]:
    warnings = []
    if local.get("ffmpeg_mux_audio_codec") == "aac" and not local.get("ffmpeg_mux_explicit_audio_bitrate"):
        warnings.append("local ffmpeg mux path uses AAC without an explicit audio bitrate")

    if upstream and upstream.get("audio_ingest_format") == "s16" and not local.get("audio_clamps_before_encode"):
        warnings.append("upstream LTX export clamps to [-1, 1] and ingests int16 before AAC encoding")

    if model_root and (model_root.get("bwe_config_found") or model_root.get("bwe_weight_keys_found")) and not local.get("vocoder_with_bwe_supported"):
        warnings.append("model root contains vocoder BWE config/weights, but local Swift reference does not support BWE")

    if model_root and model_root.get("bwe_weight_keys_found") and not model_root.get("bwe_config_found"):
        warnings.append("model root contains BWE weight keys but no JSON BWE config was found")

    local_rate = local.get("audio_sample_rate_hz")
    model_rates = model_root.get("vocoder_output_sampling_rates") if model_root else []
    if (
        local_rate
        and model_rates
        and local_rate not in model_rates
        and not local.get("passes_generation_audio_sample_rate_to_writer")
    ):
        warnings.append(f"local audio sample rate {local_rate} Hz is not among model vocoder rates {model_rates}")

    return warnings


def print_human_report(report: dict[str, Any]) -> None:
    print("LTX AV audio comparison")
    print()
    print_media_summary("mere", report["mere"])
    print_media_summary("ltx", report["ltx"])

    print("Deltas (mere - ltx)")
    for key, value in report["comparison"]["deltas_mere_minus_ltx"].items():
        print(f"  {key}: {format_value(value)}")
    print()

    refs = report["references"]
    print("Source reference")
    local = refs.get("local") or {}
    print(
        "  local: "
        f"audio_rate={format_value(local.get('audio_sample_rate_hz'))} Hz, "
        f"float_wav_stage={local.get('stages_float_wav_before_mux')}, "
        f"clamps_audio={local.get('audio_clamps_before_encode')}, "
        f"ffmpeg_aac_bitrate_explicit={local.get('ffmpeg_mux_explicit_audio_bitrate')}, "
        f"dynamic_audio_rate={local.get('passes_generation_audio_sample_rate_to_writer')}, "
        f"bwe_supported={local.get('vocoder_with_bwe_supported')}"
    )
    upstream = refs.get("ltx_repo")
    if upstream:
        print(
            "  ltx repo: "
            f"commit={upstream.get('commit')}, "
            f"audio_codec={upstream.get('encode_video_audio_codec')}, "
            f"crf={format_value(upstream.get('encode_video_default_crf'))}, "
            f"preset={upstream.get('encode_video_default_preset')}, "
            f"audio_ingest={upstream.get('audio_ingest_format')}, "
            f"bwe_supported={upstream.get('vocoder_with_bwe_supported')}"
        )
    model = refs.get("model_root")
    if model:
        print(
            "  model root: "
            f"bwe_config_found={model.get('bwe_config_found')}, "
            f"bwe_weight_keys_found={model.get('bwe_weight_keys_found')}, "
            f"vocoder_rates={model.get('vocoder_output_sampling_rates')}, "
            f"audio_rates={model.get('audio_model_sampling_rates')}"
        )
    print()

    warnings = report["warnings"]
    if warnings:
        print("Warnings")
        for warning in warnings:
            print(f"  - {warning}")
    else:
        print("Warnings: none")


def print_media_summary(label: str, report: dict[str, Any]) -> None:
    audio = report["audio_stream"]
    video = report.get("video_stream") or {}
    decoded = report["decoded_audio"]
    loudness = report["loudness"]
    print(label)
    print(
        "  video: "
        f"{video.get('codec_name')} "
        f"{format_value(video.get('width'))}x{format_value(video.get('height'))} "
        f"fps={format_value(video.get('fps'))} "
        f"frames={format_value(video.get('nb_frames'))} "
        f"duration={format_value(video.get('duration_s'))}s"
    )
    print(
        "  audio: "
        f"{audio.get('codec_name')} {format_value(audio.get('sample_rate_hz'))} Hz "
        f"{format_value(audio.get('channels'))}ch fmt={audio.get('sample_fmt')} "
        f"bitrate={format_bitrate(audio.get('bit_rate_bps'))}"
    )
    print(
        "  loudness: "
        f"I={format_db(loudness.get('integrated_lufs'), 'LUFS')} "
        f"TP={format_db(loudness.get('true_peak_dbfs'), 'dBFS')} "
        f"LRA={format_db(loudness.get('loudness_range_lu'), 'LU')}"
    )
    print(
        "  decoded: "
        f"peak={format_db(decoded.get('peak_dbfs'), 'dBFS')} "
        f"rms={format_db(decoded.get('rms_dbfs'), 'dBFS')} "
        f"crest={format_db(decoded.get('crest_db'), 'dB')} "
        f"near_clip={format_percent(decoded.get('near_clip_sample_ratio'))} "
        f"highpass/full={format_db(decoded.get('highpass_to_full_rms_db'), 'dB')}"
    )
    print()


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


def read_first_text(root: Path, relative_paths: list[str]) -> tuple[Path | None, str]:
    for relative_path in relative_paths:
        path = root / relative_path
        text = read_text(path)
        if text:
            return path, text
    return None, ""


def extract_swift_func(text: str, signature: str) -> str:
    start = text.find(signature)
    if start < 0:
        return ""
    brace = text.find("{", start)
    if brace < 0:
        return ""
    depth = 0
    for index in range(brace, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                return text[start : index + 1]
    return text[start:]


def git_commit(repo: Path) -> str | None:
    result = run_command(["git", "-C", str(repo), "rev-parse", "HEAD"])
    if result.returncode == 0:
        return result.stdout.strip()
    return None


def regex_group(pattern: str, text: str) -> str | None:
    match = re.search(pattern, text)
    return match.group(1) if match else None


def maybe_append_int(values: list[int], value: Any) -> None:
    parsed = int_or_none(value)
    if parsed is not None:
        values.append(parsed)


def int_or_none(value: Any) -> int | None:
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def float_or_none(value: Any) -> float | None:
    if value is None:
        return None
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return None
    if math.isfinite(parsed):
        return parsed
    return None


def fraction_to_float(value: Any) -> float | None:
    if not isinstance(value, str) or "/" not in value:
        return float_or_none(value)
    numerator, denominator = value.split("/", 1)
    num = float_or_none(numerator)
    den = float_or_none(denominator)
    if num is None or den in (None, 0):
        return None
    return num / den


def last_float_match(pattern: str, text: str) -> float | None:
    matches = re.findall(pattern, text)
    if not matches:
        return None
    return float_or_none(matches[-1])


def delta(left: Any, right: Any) -> float | None:
    left_float = float_or_none(left)
    right_float = float_or_none(right)
    if left_float is None or right_float is None:
        return None
    return left_float - right_float


def db(value: float) -> float:
    if value <= 0 or not math.isfinite(value):
        return float("-inf")
    return 20.0 * math.log10(value)


def none_if_inf(value: float) -> float | None:
    return value if math.isfinite(value) else None


def highpass_cutoff_for(sample_rate: int | None) -> int:
    if not sample_rate:
        return 8000
    nyquist = sample_rate / 2
    return int(max(2000, min(8000, nyquist * 0.70)))


def format_value(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, float):
        return f"{value:.4g}"
    return str(value)


def format_bitrate(value: Any) -> str:
    parsed = int_or_none(value)
    if parsed is None:
        return "n/a"
    return f"{parsed / 1000:.1f} kbps"


def format_db(value: Any, suffix: str) -> str:
    parsed = float_or_none(value)
    if parsed is None:
        return "n/a"
    return f"{parsed:.2f} {suffix}"


def format_percent(value: Any) -> str:
    parsed = float_or_none(value)
    if parsed is None:
        return "n/a"
    return f"{parsed * 100:.4f}%"


if __name__ == "__main__":
    raise SystemExit(main())
