import Foundation

public struct GeometryPLYOptions: Equatable, Sendable {
    public let maximumPointCount: Int?
    public let samplingStride: Int?

    public init(maximumPointCount: Int? = nil, samplingStride: Int? = nil) {
        self.maximumPointCount = maximumPointCount.map { max(1, $0) }
        self.samplingStride = samplingStride.map { max(1, $0) }
    }
}

public enum GeometryPLYWriter {
    public static func write(
        frame: DenseGeometryFrame,
        rgba8: [UInt8]? = nil,
        options: GeometryPLYOptions = GeometryPLYOptions(),
        to url: URL
    ) throws {
        if let rgba8, rgba8.count != frame.pixelCount * 4 {
            throw GeometryError.invalidElementCount(
                field: "point-cloud colors",
                expected: frame.pixelCount * 4,
                actual: rgba8.count
            )
        }

        let validCount = (0..<frame.pixelCount).reduce(into: 0) { count, pixel in
            if frame.isValid(pixel: pixel) { count += 1 }
        }
        guard validCount > 0 else { throw GeometryError.noValidGeometry }

        let stride: Int
        if let explicit = options.samplingStride {
            stride = explicit
        } else if let maximum = options.maximumPointCount, validCount > maximum {
            stride = max(1, Int(ceil(sqrt(Double(validCount) / Double(maximum)))))
        } else {
            stride = 1
        }

        var selected: [Int] = []
        selected.reserveCapacity(min(validCount, options.maximumPointCount ?? validCount))
        let maximum = options.maximumPointCount ?? Int.max
        for y in Swift.stride(from: 0, to: frame.height, by: stride) {
            for x in Swift.stride(from: 0, to: frame.width, by: stride) {
                let pixel = y * frame.width + x
                if frame.isValid(pixel: pixel) {
                    selected.append(pixel)
                    if selected.count == maximum { break }
                }
            }
            if selected.count == maximum { break }
        }
        guard !selected.isEmpty else { throw GeometryError.noValidGeometry }

        let hasNormals = frame.normals != nil
        let hasColors = rgba8 != nil
        let hasConfidence = frame.confidence != nil
        var header = """
        ply
        format binary_little_endian 1.0
        comment Generated by mere.run native geometry
        comment coordinate_system \(frame.coordinateSystem.rawValue)
        comment units \(frame.units.rawValue)
        element vertex \(selected.count)
        property float x
        property float y
        property float z
        """
        header += "\n"
        if hasNormals {
            header += "property float nx\nproperty float ny\nproperty float nz\n"
        }
        if hasColors {
            header += "property uchar red\nproperty uchar green\nproperty uchar blue\n"
        }
        if hasConfidence {
            header += "property float confidence\n"
        }
        header += "end_header\n"

        var data = Data(header.utf8)
        let bytesPerVertex = 12 + (hasNormals ? 12 : 0) + (hasColors ? 3 : 0) + (hasConfidence ? 4 : 0)
        data.reserveCapacity(data.count + selected.count * bytesPerVertex)
        for pixel in selected {
            let vector = pixel * 3
            appendFloat(frame.points[vector], to: &data)
            appendFloat(frame.points[vector + 1], to: &data)
            appendFloat(frame.points[vector + 2], to: &data)
            if let normals = frame.normals {
                appendFloat(normals[vector], to: &data)
                appendFloat(normals[vector + 1], to: &data)
                appendFloat(normals[vector + 2], to: &data)
            }
            if let rgba8 {
                let color = pixel * 4
                data.append(rgba8[color])
                data.append(rgba8[color + 1])
                data.append(rgba8[color + 2])
            }
            if let confidence = frame.confidence {
                appendFloat(confidence[pixel], to: &data)
            }
        }

        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try data.write(to: url, options: .atomic)
    }

    private static func appendFloat(_ value: Float, to data: inout Data) {
        var bits = value.bitPattern.littleEndian
        withUnsafeBytes(of: &bits) { data.append(contentsOf: $0) }
    }
}
