import Foundation

public enum PointCloudPLYWriter {
    public static func write(_ cloud: PointCloudAsset, to url: URL) throws {
        let hasColors = cloud.colorsRGBA8 != nil
        let hasConfidence = cloud.confidence != nil
        let hasViewIndices = cloud.viewIndices != nil
        var header = """
        ply
        format binary_little_endian 1.0
        comment Generated by mere.run native geometry
        comment coordinate_system \(cloud.coordinateSystem.rawValue)
        comment units \(cloud.units.rawValue)
        element vertex \(cloud.pointCount)
        property float x
        property float y
        property float z
        """
        header += "\n"
        if hasColors {
            header += "property uchar red\nproperty uchar green\nproperty uchar blue\nproperty uchar alpha\n"
        }
        if hasConfidence { header += "property float confidence\n" }
        if hasViewIndices { header += "property uint view_index\n" }
        header += "end_header\n"

        var data = Data(header.utf8)
        let bytesPerPoint = 12 + (hasColors ? 4 : 0) + (hasConfidence ? 4 : 0) + (hasViewIndices ? 4 : 0)
        data.reserveCapacity(data.count + cloud.pointCount * bytesPerPoint)
        for point in 0..<cloud.pointCount {
            let base = point * 3
            appendFloat(cloud.positions[base], to: &data)
            appendFloat(cloud.positions[base + 1], to: &data)
            appendFloat(cloud.positions[base + 2], to: &data)
            if let colors = cloud.colorsRGBA8 {
                data.append(contentsOf: colors[(point * 4)..<(point * 4 + 4)])
            }
            if let confidence = cloud.confidence { appendFloat(confidence[point], to: &data) }
            if let viewIndices = cloud.viewIndices { appendUInt32(viewIndices[point], to: &data) }
        }
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try data.write(to: url, options: .atomic)
    }

    private static func appendFloat(_ value: Float, to data: inout Data) {
        appendUInt32(value.bitPattern, to: &data)
    }

    private static func appendUInt32(_ value: UInt32, to data: inout Data) {
        var littleEndian = value.littleEndian
        withUnsafeBytes(of: &littleEndian) { data.append(contentsOf: $0) }
    }
}
